Fixed timing issue - time scale is drawn via GraphPanel.AxisPanel --> DateAxis.draw(..)   and draw() was incorrectly using Rectangle() to define where to draw the time axis,   with the result that the time scaling was increasingly off as you moved from left   to right.
Also added minorTickMarks to the time scale and added variable major tickmark
label spacing depending on the zoom level.

Fixed lines in ViewPSD that were causing the PSD button to generate runtime error:
java.lang.IllegalArgumentException: This dataset already contains a series with the key ("MODEL")

This error only occured with the latest (e.g., v1.0.14) versions of jfreechart lib, which
do NOT allow more than one XYSeries("keyname") per XYSeriesCollection.
e.g., you can't do XYSeriesCollection.addSeries() twice on 2 series with the same keyname.
The keyname must be unique.

Now it is possible to use the latest versions of jfreechart lib.